kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    imagerigestry: "https://dockerhub.com"
    buildURL: "https://jenkins.com/job/1234"
  spec:
  containers:
  - name: nginx
    image: nginx
      