---
apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        limits:
          cpu: 100m
          memory: 68Mi
        requests:
          cpu: 120m
          memory: 100Mi