---
apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        limits:
          cpu: 100mi
          memory: 120Mi
        memory: 100Mi
        requests:
          cpu: 68mi