---
apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        limits:
          cpu: 100m
          memory: 120Mi
        requests:
          cpu: 68m
          memory: 100Mi