kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: pod-secret
      