---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  ports:
    - name: nginx-svc-ports
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    environment: dev
    module: backend
    project: expense
  type: LoadBalancer